=== TambourineReindeer/netbeans-opengl-pack/native-lib-support/src/net/java/nativelibsupport/natives-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/natives-config"
            xmlns:tns="http://xml.netbeans.org/schema/natives-config"
            elementFormDefault="qualified">
    <xsd:element name="library">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="folder" type="xsd:string"/>
                <xsd:element name="distribution" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="os">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="folder" type="xsd:string"/>
                                        <xsd:element name="regexp" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="cpu">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="folder" type="xsd:string"/>
                                        <xsd:element name="regexp" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== TambourineReindeer/netbeans-opengl-pack/native-lib-support/test/unit/src/net/java/nativelibsupport/test-natives-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : natives-config.xml
    Created on : April 10, 2008, 6:36 PM
    Author     : mbien
    Description:
        Nativle library deployment configuration file.
-->
<ns0:library  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://net/java/nativelibsupport/natives_config'
   xsi:schemaLocation='http://net/java/nativelibsupport/resource natives-config.xsd'
   name='jogl.jar' folder='jogl-runtime' flat='true'>
    <ns0:os folder='-natives-windows' regexp='^windows'>
        <ns0:cpu folder='-amd64' regexp='^amd|x64|x86_64$'/>
        <ns0:cpu folder='-i586' regexp='^i?+[3-9|x]86$'/>
    </ns0:os>
    <ns0:os folder='-natives-macosx' regexp='^mac'>
        <ns0:cpu folder='-ppc' regexp='^ppc$'/>
        <ns0:cpu folder='-universal' regexp='.'/>
    </ns0:os>
    <ns0:os folder='-natives-linux' regexp='^linux'>
        <ns0:cpu folder='-amd64' regexp='^amd|x64|x86_64$'/>
        <ns0:cpu folder='-i586' regexp='^i?+[3-9|x]86$'/>
    </ns0:os>
    <ns0:os folder='-natives-solaris' regexp='^(?i)solaris|sunos'>
        <ns0:cpu folder='-amd64' regexp='^amd|x64|x86_64$'/>
        <ns0:cpu folder='-sparc' regexp='^sparc$'/>
        <ns0:cpu folder='-sparcv9' regexp='^sparcv9$'/>
        <ns0:cpu folder='-i586' regexp='^i?+[3-9|x]86$'/>
    </ns0:os>
</ns0:library>

=== TambourineReindeer/netbeans-opengl-pack/jogl/src/net/java/nboglpack/jogl/newt-natives-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : natives-config.xml
    Created on : April 10, 2008, 6:36 PM
    Author     : mbien
    Description:
        Nativle library deployment configuration file.
-->
<ns0:library  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://net/java/nativelibsupport/natives_config'
   xsi:schemaLocation='http://net/java/nativelibsupport/resource natives-config.xsd'
   name='newt.jar' folder='jogl-runtime' flat='true'>
    <ns0:os folder='-natives-windows' regex='^(?i)windows'>
        <ns0:cpu folder='-amd64' regex='^(?i)amd|x64|x86_64$'/>
        <ns0:cpu folder='-i586' regex='^(?i)i?+[3-9|x]86$'/>
    </ns0:os>
    <ns0:os folder='-natives-macosx' regex='^(?i)mac'>
        <ns0:cpu folder='-ppc' regex='^(?i)ppc$'/>
        <ns0:cpu folder='-universal' regex='.'/>
    </ns0:os>
    <ns0:os folder='-natives-linux' regex='^(?i)linux'>
        <ns0:cpu folder='-amd64' regex='^(?i)amd|x64|x86_64$'/>
        <ns0:cpu folder='-i586' regex='^(?i)i?+[3-9|x]86$'/>
    </ns0:os>
    <ns0:os folder='-natives-solaris' regex='^(?i)solaris|sunos'>
        <ns0:cpu folder='-amd64' regex='^(?i)amd|x64|x86_64$'/>
        <ns0:cpu folder='-sparc' regex='^(?i)sparc$'/>
        <ns0:cpu folder='-sparcv9' regex='^(?i)sparcv9$'/>
        <ns0:cpu folder='-i586' regex='^(?i)i?+[3-9|x]86$'/>
    </ns0:os>
</ns0:library>

=== TambourineReindeer/netbeans-opengl-pack/native-lib-support/src/net/java/nativelibsupport/test-natives-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : natives-config.xml
    Created on : April 10, 2008, 6:36 PM
    Author     : mbien
    Description:
        Purpose of the document follows.
-->
<ns0:library 
   xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/natives-config'
   xsi:schemaLocation='http://xml.netbeans.org/schema/natives-config natives-config.xsd'>
    <ns0:name>JOGL</ns0:name>
    <ns0:folder>jogl-runtime</ns0:folder>
    <ns0:distribution>
        <ns0:os>
            <ns0:folder>linux</ns0:folder>
            <ns0:regexp>asdf</ns0:regexp>
        </ns0:os>
        <ns0:cpu>
            <ns0:folder>amd64</ns0:folder>
            <ns0:regexp>asdf</ns0:regexp>
        </ns0:cpu>
    </ns0:distribution>
</ns0:library>
